import Vue from 'vue'
import Vuex from 'vuex'
import axios from 'axios'

Vue.use(Vuex)

export const store = new Vuex.Store({

  state:{
    depts: [
        {
          value: '儿科康复',
          label: '儿科康复'
        },
        {
          value: '日间手术室',
          label: '日间手术室'
        },
        {
          value: '重症医学科',
          label: '重症医学科'
        },
        {
          value: '心胸外科',
          label: '心胸外科'
        },
        {
          value: '口腔颌面外科',
          label: '口腔颌面外科'
        },
        {
          value: '骨外四科',
          label: '骨外四科'
        },
        {
          value: '普外一科',
          label: '普外一科'
        },
        {
          value: '普外二科',
          label: '普外二科'
        },
        {
          value: '普外三科',
          label: '普外三科'
        },
        {
          value: '骨外一科',
          label: '骨外一科'
        },
        {
          value: '骨外二科',
          label: '骨外二科'
        },
        {
          value: '骨外三科',
          label: '骨外三科'
        },
        {
          value: '妇一科',
          label: '妇一科'
        },
        {
          value: '妇二科',
          label: '妇二科'
        },
        {
          value: '产科',
          label: '产科'
        },
        {
          value: '泌尿外科',
          label: '泌尿外科'
        },
        {
          value: '神内一科',
          label: '神内一科'
        },
        {
          value: '神内二科',
          label: '神内二科'
        },
        {
          value: '心内一科',
          label: '心内一科'
        },
        {
          value: '心内二科',
          label: '心内二科'
        },
        {
          value: '呼吸一科',
          label: '呼吸一科'
        },
        {
          value: '消化一科',
          label: '消化一科'
        },
        {
          value: '神内三科',
          label: '神内三科'
        },
        {
          value: '血液内科',
          label: '血液内科'
        },
        {
          value: '核医学科',
          label: '核医学科'
        },
        {
          value: '神经外科',
          label: '神经外科'
        },
        {
          value: '消化二科',
          label: '消化二科'
        },
        {
          value: '耳鼻喉-头颈外科',
          label: '耳鼻喉-头颈外科'
        },
        {
          value: '心内三科',
          label: '心内三科'
        },
        {
          value: '儿一科',
          label: '儿一科'
        },
        {
          value: '儿二科',
          label: '儿二科'
        },
        {
          value: '儿科NICU',
          label: '儿科NICU'
        },
        {
          value: '儿科PICU',
          label: '儿科PICU'
        },
        {
          value: '呼吸二科',
          label: '呼吸二科'
        },
        {
          value: '内分泌科',
          label: '内分泌科'
        },
        {
          value: '皮肤科',
          label: '皮肤科'
        },
        {
          value: '综合外科',
          label: '综合外科'
        },
        {
          value: '眼科',
          label: '眼科'
        },
        {
          value: '中医科',
          label: '中医科'
        },
        {
          value: '疼痛科',
          label: '疼痛科'
        },
        {
          value: '临床营养科',
          label: '临床营养科'
        },
        {
          value: '肿瘤一科',
          label: '肿瘤一科'
        },
        {
          value: '康复科',
          label: '康复科'
        },
        {
          value: '肿瘤三科',
          label: '肿瘤三科'
        },
        {
          value: '肿瘤二科',
          label: '肿瘤二科'
        },
        {
          value: '肿瘤五科',
          label: '肿瘤五科'
        },
        {
          value: '肿瘤四科',
          label: '肿瘤四科'
        },
        {
          value: '风湿免疫科',
          label: '风湿免疫科'
        },
        {
          value: '肾病内科',
          label: '肾病内科'
        }
      ],
    employee_template: {
      "doc_id":"doc_1",
      "doc_code":"employee_survey",
      "doc_name":"襄阳中心医院职工满意度调查",
      "doc_advice":"",
      "doc_dept":[
        {
          "dept_id":"dept_1",
          "dept_code":"yigaiban",
          "dept_name":"医改办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_2",
          "dept_code":"yuanban",
          "dept_name":"院办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_3",
          "dept_code":"dangban",
          "dept_name":"党办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_4",
          "dept_code":"xuanchuangbu",
          "dept_name":"宣传部",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_5",
          "dept_code":"renliziyuanchu",
          "dept_name":"人力资源处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_6",
          "dept_code":"jianshenchu",
          "dept_name":"监审处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_7",
          "dept_code":"qungongbu",
          "dept_name":"群工部",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_8",
          "dept_code":"laoganbuchu",
          "dept_name":"老干部处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_9",
          "dept_code":"yiwuchu",
          "dept_name":"医务处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_10",
          "dept_code":"hulibu",
          "dept_name":"护理部",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_11",
          "dept_code":"zhikongban",
          "dept_name":"质控办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_12",
          "dept_code":"gankongban",
          "dept_name":"感控办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_13",
          "dept_code":"gonggongweishengchu",
          "dept_name":"公共卫生处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_14",
          "dept_code":"menzhenbu",
          "dept_name":"门诊部",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_15",
          "dept_code":"keyanchu",
          "dept_name":"科研处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_16",
          "dept_code":"linchuangxueyuanjiaoyujiaoxueban",
          "dept_name":"临床学院教育教学办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_17",
          "dept_code":"linchuangxueyuanhulixi",
          "dept_name":"临床学院护理系",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_18",
          "dept_code":"jixujiaoyubangongsi",
          "dept_name":"继续教育办公室",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_19",
          "dept_code":"yibaoban",
          "dept_name":"医保办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_20",
          "dept_code":"duiwaiguanxibu",
          "dept_name":"对外关系部",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_21",
          "dept_code":"xinxiguanlichu",
          "dept_name":"信息管理处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_22",
          "dept_code":"zongwuchu",
          "dept_name":"总务处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_23",
          "dept_code":"shebeichu",
          "dept_name":"设备处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_24",
          "dept_code":"caiwuchu",
          "dept_name":"财务处(国资办)",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_25",
          "dept_code":"jingguanban",
          "dept_name":"经管办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_26",
          "dept_code":"zhaobiaoban",
          "dept_name":"招标办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_27",
          "dept_code":"jijianban",
          "dept_name":"基建办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_28",
          "dept_code":"baoweichu",
          "dept_name":"保卫处",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_29",
          "dept_code":"ganbubaojianke",
          "dept_name":"干部保健科",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_30",
          "dept_code":"dongjingyuanquzongheban",
          "dept_name":"东津院区综合办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        },{
          "dept_id":"dept_31",
          "dept_code":"beiyuanquzongheban",
          "dept_name":"北院区综合办",
          "dept_group":[
            {
              "group_id":"group_1",
              "group_code":"basic_survey",
              "group_name":"基本情况调查",
              "group_item":[
                {
                  "item_id":"item_1",
                  "item_code":"attitude",
                  "item_name":"服务态度",
                  "item_star":0
                },{
                  "item_id":"item_2",
                  "item_code":"efficiency",
                  "item_name":"办事效率",
                  "item_star":0
                },{
                  "item_id":"item_3",
                  "item_code":"quality",
                  "item_name":"服务质量",
                  "item_star":0
                },{
                  "item_id":"item_4",
                  "item_code":"discipline",
                  "item_name":"劳动纪律",
                  "item_star":0
                }
              ]
            }
          ]
        }
      ]
    },
    zgdcha:{
      zgyjian:'',
      zgbmen:[
      {
        dept:'院办',
        dcha:[0,0,0,0]
      },
      {
        dept:'党办',
        dcha:[0,0,0,0]
      },
      {
        dept:'人力资源部',
        dcha:[0,0,0,0]
      },
      {
        dept:'监审处',
        dcha:[0,0,0,0]
      },
      {
        dept:'医务处',
        dcha:[0,0,0,0]
      },
      {
        dept:'护理部',
        dcha:[0,0,0,0]
      },
      {
        dept:'宣传部',
        dcha:[0,0,0,0]
      },
      {
        dept:'院工会',
        dcha:[0,0,0,0]
      },
      {
        dept:'财务处',
        dcha:[0,0,0,0]
      },
      {
        dept:'医保办',
        dcha:[0,0,0,0]
      },
      {
        dept:'科研教学科',
        dcha:[0,0,0,0]
      },
      {
        dept:'质控办',
        dcha:[0,0,0,0]
      },
      {
        dept:'院感办',
        dcha:[0,0,0,0]
      },
      {
        dept:'信息管理处',
        dcha:[0,0,0,0]
      },
      {
        dept:'设备处',
        dcha:[0,0,0,0]
      },
      {
        dept:'总务处',
        dcha:[0,0,0,0]
      },
      {
        dept:'维修班',
        dcha:[0,0,0,0]
      },
      {
        dept:'电工班',
        dcha:[0,0,0,0]
      },
      {
        dept:'管道班',
        dcha:[0,0,0,0]
      },
      {
        dept:'招标办',
        dcha:[0,0,0,0]
      },
      {
        dept:'收费室',
        dcha:[0,0,0,0]
      },
      {
        dept:'统计室',
        dcha:[0,0,0,0]
      },
      {
        dept:'基建办',
        dcha:[0,0,0,0]
      },
      {
        dept:'门诊部',
        dcha:[0,0,0,0]
      }
    ]
    },
    yji:{
      yjyjian:'',
      yjkshi:[
        {dept:'',dcha:[]}
      ]
    }
  },
  getters:{
    EmployeeSurvey:function (state) {
      //state.actions.getEmployeeTemplate();
      return state.employee_template
    },
    DEPTS:function(state){
      return state.depts
    },
    zgdcha:function(state){
      return state.zgdcha
    }
  },
  actions:{
    /*getEmployeeTemplate:function (context) {
      context.commit("EmployeeTemplate")
    }*/
  },
  mutations:{
    /*EmployeeTemplate:function(state){
      axios.get("/template/employee")
        .then(function (data) {
          if(data.status==200){
            state.employee_template=data.data
            //console.log(employee_template)
          }
        })
    },*/
  }
})
